//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PestPac_Utility.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PestPac_Utility.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;10000 :=: 94322&quot;
        ///&quot;115954 :=: 141190&quot;
        ///&quot;514336 :=: 142858&quot;
        ///&quot;115966 :=: 148496&quot;
        ///&quot;115972 :=: 168977&quot;
        ///&quot;115973 :=: 168978&quot;
        ///&quot;115974 :=: 171959&quot;
        ///&quot;105274 :=: 14948&quot;
        ///&quot;115976 :=: 173144&quot;
        ///&quot;401726 :=: 14906&quot;
        ///&quot;401728 :=: 15304&quot;
        ///&quot;401729 :=: 15305&quot;
        ///&quot;401727 :=: 15301&quot;
        ///&quot;401730 :=: 15308&quot;
        ///&quot;401731 :=: 15311&quot;
        ///&quot;403135 :=: 25703&quot;
        ///&quot;403136 :=: 25704&quot;
        ///&quot;403137 :=: 25705&quot;
        ///&quot;403138 :=: 25706&quot;
        ///&quot;403139 :=: 25707&quot;
        ///&quot;403140 :=: 25708&quot;
        ///&quot;403141 :=: 25709&quot;
        ///&quot;403142 :=: 25710&quot;
        ///&quot;403143 :=: 25711&quot;
        ///&quot;403144 :=: 25712&quot;
        ///&quot;40314 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LocationCodes {
            get {
                return ResourceManager.GetString("LocationCodes", resourceCulture);
            }
        }
    }
}
