using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DBDLib
{
    public static class Collections
    {
        public static readonly string[] KILLER_PERKS = new string[]
        {
            "Barbecue & Chili",
            "Hex: Ruin",
            "A Nurse's Calling",
            "Enduring",
            "Make Your Choice",
            "Hex: No One Escapes Death",
            "Whispers",
            "Monitor & Abuse",
            "Franklin's Demise",
            "Agitation",
            "Brutal Strength",
            "Overcharge",
            "Remember Me",
            "Deerstalker",
            "Hex: Devour Hope",
            "Tinkerer",
            "Thanatophobia",
            "Stridor",
            "Lightborn",
            "Unnerving Presence",
            "Knock Out",
            "Hex: Thrill of the Hunt",
            "Hex: Huntress Lullaby",
            "Iron Grasp",
            "Distressing",
            "Blood Warden",
            "Hangman's Trick",
            "Shadowborn",
            "Dying Light",
            "Bloodhound",
            "Insidious",
            "Overwhelming Presence",
            "Spies From The Shadows",
            "Fire Up",
            "Hex: The Third Seal",
            "Unrelenting",
            "Territorial Imperative",
            "Play With Your Food",
            "Sloppy Butcher",
            "Bitter Murmur",
            "Beast Of Prey",
            "Surveillance",
            "Save The Best For Last",
            "Predator",
            "Monstrous Shrine"
        };

        public static readonly string[] SURVIVOR_PERKS = new string[]
        {
            "Self-Care",
            "Sprint Burst",
            "Borrowed Time",
            "Iron Will",
            "Urban Evasion",
            "Decisive Strike",
            "Bond",
            "Dead Hard",
            "Lithe",
            "Empathy",
            "We'll Make It",
            "Adrenaline",
            "Quick & Quiet",
            "Kindred",
            "Plunderer's Instinct",
            "Leader",
            "Lightweight",
            "We're Gonna Live Forever",
            "Unbreakable",
            "Stake Out",
            "Vigil",
            "Tenacity",
            "Spine Chill",
            "Premonition",
            "Botany Knowledge",
            "Balanced Landing",
            "Pharmacy",
            "Object of Obsession",
            "Up The Ante",
            "Detective's Hunch",
            "Ace in The Hole",
            "Saboteur",
            "Open Handed",
            "Technician",
            "Streetwise",
            "Alert",
            "Resilience",
            "Small Game",
            "Slippery Meat",
            "Wake Up!",
            "Hope",
            "Sole Survivor",
            "Prove Thyself",
            "No Mither",
            "No One Left Behind",
            "Dark Sense",
            "Calm Spirit",
            "This Is Not Happening",
            "Left Behind",
            "Déjà Vu"
        };
    }
}
