using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DnDLib.Models
{
    public enum MonsterType : byte
    {
        None,
        Aberration,
        Beast,
        Celestial,
        Construct,
        Dragon,
        Elemental,
        Fey,
        Fiend,
        Giant,
        Humanoid,
        Monstrosity,
        Ooze,
        Plant,
        Undead,
        Unknown
    }

    public enum MonsterSubtype : byte
    {
        None = 0,
        Aarakocra = 1,
        Angel = 47,
        Any_Race = 5,
        Bullywug = 41,
        Cloud_Giant = 35,
        Demon = 9,
        Derro = 17,
        Devil = 10,
        Dragonborn = 54,
        Dwarf = 16,
        Elf = 6,
        Fire_Giant = 36,
        Firenewt = 27,
        Frost_Giant = 37,
        Gith = 15,
        Gnoll = 3,
        Gnome = 2,
        Goblinoid = 23,
        Grimlock = 4,
        Grung = 25,
        Half_Dragon = 45,
        Half_Elf = 44,
        Halfling = 51,
        Half_Orc = 50,
        Hill_Giant = 38,
        Human = 33,
        Inevitable = 14,
        Kenku = 26,
        Kobold = 24,
        Kraul = 48,
        Kuo_Toa = 18,
        Lizardfolk = 34,
        Locathah = 52,
        Meazel = 13,
        Merfolk = 32,
        Nagpa = 12,
        Orc = 22,
        Quaggoth = 31,
        Sahuagin = 30,
        Saurial = 42,
        Shapechanger = 11,
        Simic_Hybrid = 46,
        Stone_Giant = 39,
        Storm_Giant = 40,
        Tabaxi = 43,
        Thri_Keen = 29,
        Tiefling = 49,
        Titan = 19,
        Tortle = 7,
        Triton = 53,
        Troglodyte = 28,
        Xvart = 21,
        Yuan_Ti = 20,
        Yugoloth = 8
    }
    
    public enum MonsterTags
    {
        Abberation = 130,
        Angel = 60,
        Armor = 27,
        Artificer = 212,
        Azorius = 176,
        Beholder = 71,
        Boros = 174,
        Cloud_Giant = 156,
        Construct = 131,
        Cult_of_the_Black_Earth = 92,
        Cult_of_the_Crushing_Wave = 94,
        Cult_of_the_Dragon = 96,
        Cult_of_the_Eternal_Flame = 93,
        Cult_of_the_Howling_Hatred = 91,
        Demon = 59,
        Demon_Lord = 89,
        Devil = 58,
        Dimir = 182,
        Dinosaur = 61,
        Dwarf = 136,
        Elemental = 138,
        Elf = 134,
        Fey = 137,
        Fiend = 133,
        Fungus = 77,
        Genie = 76,
        Gith = 142,
        Gnoll = 80,
        Goblinoid = 64,
        Golgari = 181,
        Grung = 81,
        Gruul = 180,
        Hag = 82,
        Half_Elf = 158,
        Half_Orc = 164,
        Human = 157,
        Humanoid = 135,
        Inevitable = 153,
        Izzet = 177,
        Kobold = 83,
        Meazel = 140,
        Mind_Flayer = 84,
        Misc_Creature = 57,
        Modron = 78,
        Monastery_of_the_Distressed_Body = 211,
        Monstrosity = 141,
        Myconid = 79,
        Naga = 74,
        Nagpa = 139,
        NPC = 52,
        Obzedat = 185,
        Orc = 85,
        Orzhov = 175,
        Plant = 132,
        Prince_of_Elemental_Evil = 95,
        Rakdos = 179,
        Red_Wizard = 97,
        Rogue = 117,
        Selesnya = 178,
        Shapechanger = 63,
        Sidekick = 250,
        Simic = 183,
        Slaad = 73,
        Titan = 62,
        Undead = 129,
        Yuan_Ti = 75,
        Yugoloth = 70
    }

    public enum Size : byte
    {
        None,
        Tiny = 2,
        Small,
        Medium,
        Large,
        Huge,
        Gargantuan
    }
}
